### ISSUE TITLE
Ads on `hindifiber.com`

### ISSUE THREAD

**Issue by eporubin** [mediumkreation/IndianList#8113]
Hi 👋  could you please check out this domain for example on this article: `https://hindifiber.com/suzlon-energy-new-target-price-news2oct/` there are a couple of ads: 
- embedded in the content can be hidden with this filter `hindifiber.com##.wp-block-image`
<img width="1080" alt="image" src="https://github.com/mediumkreation/IndianList/assets/33602691/d014633c-7e9f-4765-bc31-9f238de2611c">
-  LHK ads widget at the bottom of the article, can be hidden with this filter `hindifiber.com##.lhk-ads-container`
<img width="1080" alt="image" src="https://github.com/mediumkreation/IndianList/assets/33602691/cd4e9347-535b-4b07-8402-1db02a451fa5">
Thank you

**Comment by mediumkreation** [comment]
fixed: #8126

**Comment by eporubin** [comment]
Hi @mediumkreation please reopen the issue  I can still see the big banner ad embedded on the page please just use `hindifiber.com##.wp-block-image` to hide it. 
Regards,

**Comment by mediumkreation** [comment]
> Hi @mediumkreation please reopen the issue I can still see the big banner ad embedded on the page please just use `hindifiber.com##.wp-block-image` to hide it. Regards,

@eporubin using `hindifiber.com##.wp-block-image` will also hide content images.

**Comment by eporubin** [comment]
> > Hi @mediumkreation please reopen the issue I can still see the big banner ad embedded on the page please just use `hindifiber.com##.wp-block-image` to hide it. Regards,
> 
> @eporubin using `hindifiber.com##.wp-block-image` will also hide content images.

@mediumkreation  I didnt see any breakage then testing but alright maybe I missed something, Thanks for finding a way to fix it anyway 🙌
